# Site settings
title: coffeeml
email: 
description: personal website, documenting by experiences and opinionated views on things I'm interested in (mostly AI, finance and software engineering).
baseurl: ""
url: "https://coffeeml.github.io"
linkedin_username: 
github_username:  coffeeml
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  somefolder:
    output: true
