# Site settings
title: ok! saurav
email: 
description: personal website, documenting my experiences and opinionated views on things I'm interested in.
baseurl: ""
url: "https://oksaurav.github.io"
linkedin_username: 
github_username:  oksaurav
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  somefolder:
    output: true
