# Site settings
title: shutup joe!
email: 
description: personal website, documenting my experiences and opinionated views on things I'm interested in
baseurl: ""
url: "https://shutupjoe.github.io"
linkedin_username: 
github_username:  agent1oop
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  somefolder:
    output: true
