# Site settings
title: saurav dey
email: 
description: Opinionated views on agentic AI and software engineering.
baseurl: ""
url: "https://deysaurav.github.io"
linkedin_username: 
github_username:  rxrav
twitter_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

include:
 - _pages 

collections:
  somefolder:
    output: true
